runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: html/index.html
  upload: html/index.html

- url: /(.*)
  static_files: html/\1
  upload: html/(.*)

- url: /html
  static_files: html/\1
  upload: html

- url: /img
  static_files: img/\1
  upload: img

- url: /css
  static_files: css/\1
  upload: css

- url: /fontawesome
  static_files: fontawesome/\1
  upload: fontawesome