runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: html/index.html
  upload: html/index.html

- url: /html
  static_dir: html

- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /fontawasome
  static_dir: fontawasome